### ISSUE TITLE
"An error occured while publishing" bug

### ISSUE THREAD

**Issue by chloeatplay** [toolness/mobile-microgame-maker#17]
Getting more than once an error occured while publishing message on safari, on my ipad.

**Comment by toolness** [comment]
It should say the name of the error that occurred when publishing, I think? Does it always say `timeout` like you mentioned in #18, or does it occasionally say other things?

If it always says timeout, then this is a duplicate of #14...

**Comment by toolness** [comment]
Talked to Chloe and it looks like this is indeed a duplicate of #14.
