### ISSUE TITLE
Update font + message for "win+loose" messages

### ISSUE THREAD

**Issue by chloeatplay** [toolness/mobile-microgame-maker#25]
![mobile minigame maker 2015-01-11 17-05-09](https://cloud.githubusercontent.com/assets/1945209/5697066/0b34ae24-99b4-11e4-9cf1-504bfdb46140.png)

Can this also be Fredoka and the text for

Win " Woohoo! You Won"
Loose " Uh-Oh! You Lost"

**Comment by toolness** [comment]
Ah, that's actually just debug text--it won't show up in the final exported game... I guess it might be better to move that debug text out of the game frame and to some place outside of the frame?

Hmm, alternatively, we could initialize new games with a tiny bit of blockly code that sets a default win/lose condition, e.g.:

![capture](https://cloud.githubusercontent.com/assets/124687/5792514/ecb59856-9ee9-11e4-866c-50bcd78e6128.PNG)

That way there's also at least a little bit of initial blockly code that the user can tinker with, which might help onboard them a bit better than a completely blank slate.

**Comment by chloeatplay** [comment]
I love the default text- yupiee dupiee 

## and agree maybe the debug text doesn’t show

On January 18, 2015 at 8:15:41 AM, Atul Varma (notifications@github.com) wrote:

Ah, that's actually just debug text--it won't show up in the final exported game... I guess it might be better to move that debug text out of the game frame and to some place outside of the frame?

Hmm, alternatively, we could initialize new games with a tiny bit of blockly code that sets a default win/lose condition, e.g.:

That way there's also at least a little bit of initial blockly code that the user can tinker with, which might help onboard them a bit better than a completely blank slate.
